# Generated by Django 2.2.8 on 2020-02-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urls',
            old_name='main_ap',
            new_name='urls',
        ),
        migrations.AddField(
            model_name='urls',
            name='for_check',
            field=models.BooleanField(default=True),
        ),
    ]
