# Generated by Django 2.2.8 on 2020-02-19 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200219_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='check',
            field=models.BooleanField(default=True),
        ),
    ]
